name: lazy_chores
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  flutter: 3.16.9
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: 8.1.2
  cached_annotation: 1.6.0
  chopper: 7.1.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_hooks: 0.20.4
  freezed_annotation: 2.4.1
  get_it: 7.6.7
  go_router: 13.1.0
  injectable: 2.3.2
  json_annotation: 4.8.1

dev_dependencies:
  bloc_test: 9.1.5
  build_runner: 2.4.8
  cached: 1.6.4
  chopper_generator: 7.1.1
  flutter_gen_runner: 5.4.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.4.6
  injectable_generator: 2.4.1
  json_serializable: 6.7.1
  linteo: 1.3.0
  mocktail: 1.0.3

flutter_gen:
  output: lib/presentation/common/gen/
  line_length: 120
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    enabled: true
  fonts:
    enabled: false
  colors:
    enabled: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400