name: lazy_chores
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: 3.16.2
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: 8.1.2
  injecteo: 1.0.0
  chopper: 7.0.9
  freezed_annotation: 2.4.1
  flutter_hooks: 0.20.3
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.4.7
  chopper_generator: 7.0.6
  injecteo_generator: 1.0.1
  json_serializable: 6.7.1
  freezed: 2.4.5
  bloc_test: 9.1.5
  mocktail: 1.0.1
  architecture_linter: 0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/