name: lazy_chores
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: 3.16.5
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  bloc: 8.1.2
  chopper: 7.0.9
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_hooks: 0.20.3
  freezed_annotation: 2.4.1
  injecteo: 1.0.0
  json_annotation: 4.8.1
  linteo:
    path: /Users/kfalinski/development/opensource_repos/linteo

dev_dependencies:
  architecture_linter: 0.2.0
  bloc_test: 9.1.5
  build_runner: 2.4.7
  chopper_generator: 7.0.6
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  injecteo_generator: 1.0.1
  json_serializable: 6.7.1
  mocktail: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/